### ISSUE TITLE
Team-elmos-125 code review - Jun 26th 2020

### ISSUE THREAD

**Issue by mohammadumar28** [rahalrazika/The-Next-web#2]
* Use CSS variables to maintain the project easily. 🗳️ 
* Use semantic elements (make use of anchor tags when necessary). ⚓ 
* Use the mobile-first approach while designing the web page. 📱 
* Design Fonts and add spacing like the original website.

**Comment by descholar-ceo** [comment]
You have a great job @mohammadumar28 and @rahalrazika , special congrats
